Fixed metis script and meshes

diff --git a/meshes/metis_script b/meshes/metis_script
--- a/meshes/metis_script
+++ b/meshes/metis_script
@@ -10,13 +10,30 @@ sed -n '/Tetrahedra/,/Triangles/p' $1 | sed '1d;$d' | sed '$d' | sed 's/ 0//' > 
 # launch metis
 mpmetis -ncommon=3 -minconn -contig metis_input $2
 
+# check metis output
+echo "Checking missing polyhedra..."
+end=$(($2-1))
+ii=0
+while [ $ii -le $end ]; do
+  grep -q -w $ii metis_input.epart.$2
+  # if there isnt't the polyhedron ii I have to decrease the total number and to
+  # substitute the previous last polyhedron with the number ii
+  if [ $? -eq 1 ]; then
+    awk -i inplace -v miss=$ii '{if($1>miss) $1--; print}' metis_input.epart.$2
+    let end-=1
+  fi
+  let ii+=1
+done
+echo "Polyhedra after check: "$((end+1))
+echo "******************************************************************************"
+
 # create the file with the final mesh
 final_name="$(echo $1 | cut -f 1 -d '.')_metis.mesh"
 sed '/Triangles/,/-End/d' $1 > $final_name
 
 # add metis output
 echo "Polyhedra" >> $final_name
-echo $2 >> $final_name
+echo $((end+1)) >> $final_name
 cat metis_input.epart.$2 >> $final_name
 echo "" >> $final_name
 echo End >> $final_name
